[package]
name = "flv"
version = "0.1.0"
authors = ["Mr.Panda<xivistudios@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.42"
chrono = "0.4"
regex = "1"
woothee = "*"

[dependencies.web-sys]
version = "0.3.4"
features = [
  "Window",
  "Navigator"
]